[package]
name = "peerless-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "peerless"
path = "src/main.rs"

[dependencies]
peerless-compute = { path = "../peerless-compute" }
peerless-core = { path = "../peerless-core" }
libp2p.workspace = true
peerless-network = { path = "../peerless-network" }
peerless-node = { path = "../peerless-node" }
peerless-ledger = { path = "../peerless-ledger" }
qrcode.workspace = true
serde_json.workspace = true
wat.workspace = true
