[package]
name = "peerless-state"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
automerge.workspace = true
peerless-storage = { path = "../peerless-storage" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
